on:
  push:
  pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - uses: "actions/setup-node@v4"
        with:
          node-version: 20

      - run: "yarn --frozen-lockfile"

      - run: "yarn build"

      - run: "yarn lint"

      - run: "yarn test"

      - uses: "actions/upload-artifact@v4"
        if: failure()
        with:
          name: "terminal-screenshot-tests"
          path: "/tmp/terminal-screenshot-tests/" # __SCREENSHOT_TEST_FAILURES_DIR__
          if-no-files-found: "ignore"

      - run: "yarn semantic-release"
        env:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
