on:
  push:
    branches: [release]

jobs:
  build:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn --frozen-lockfile
      - run: yarn semantic-release --dry-run
